version: '3.7'

services:
  fe:
    image: veda50/sparka-fe:multi-platform
    ports:
      - "3000:3000"
    environment:
      - SESSION_SECRET=jeruk
      - API_URL=http://be:8080
    # networks:
    #   - app-network

  be:
    image: veda50/sparka-be:multi-platform
    ports:
      - "8000:8080"
    depends_on:
      - mysql
    environment:
      - APP_NAME=Lumen
      - APP_ENV=local
      - APP_KEY=base64:nZ+Z5gHUZm//QxXF3oDsHyWxwYrn6Tc6346IYRr2J5U=
      - APP_DEBUG=true
      - APP_URL=http://be:8000
      - APP_TIMEZONE=UTC
      - LOG_CHANNEL=stack
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=hyparkdb
      - DB_USERNAME=app
      - DB_PASSWORD=sparkabe
      - JWT_SECRET=jeruk
    command: /bin/sh -c "php artisan migrate --seed && php-fpm"
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sparkabe  # Ganti dengan password root MySQL Anda
      MYSQL_DATABASE: hyparkdb
      MYSQL_USER: app
      MYSQL_PASSWORD: sparkabe
    ports:
      - "3001:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYTViYjA4MTI1MWM4YmM1OTJmNGUzZGU2NWY1OGRiNGIiLCJ0IjoiOTRhMDgxYjYtZmVkYi00ZTQzLWIwNDYtM2EyMDJmYTE2YzZlIiwicyI6Ik5HUXpOalUxT1RndE1HSXpNeTAwT0dGa0xXRmpPV1l0TnpCaU1ERXhZekExTkRkbSJ9
    networks:
      - app-network
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
